// Generated by CoffeeScript 1.9.3
(function() {
  var _ajax, _utilities, all;

  _utilities = require('../utilities');

  _ajax = require('../ajax');

  all = function() {
    return _ajax.get('/api/' + _utilities.pluralKebabCase(this.name));
  };

  module.exports = all;

}).call(this);
