// Generated by CoffeeScript 1.9.3
(function() {
  var _ajax, _utilities, all;

  _utilities = require('../utilities');

  _ajax = require('../ajax');

  all = function(limit) {
    if (!limit) {
      limit = 0;
    }
    return _ajax.get.apply(this, [
      '/api/' + _utilities.pluralKebabCase(this.className), {
        limit: limit
      }
    ]);
  };

  module.exports = all;

}).call(this);
