// Generated by CoffeeScript 1.9.3
(function() {
  var _, _ajax, create;

  _ = require('lodash');

  _ajax = require('../ajax');

  create = function(opts) {
    return _ajax.post.apply(this, ['/api/' + _.kebabCase(this.className), opts]);
  };

  module.exports = create;

}).call(this);
