// Generated by CoffeeScript 1.9.3
(function() {
  var _, _ajax, find;

  _ = require('lodash');

  _ajax = require('../ajax');

  find = function(id) {
    return _ajax.get('/api/' + _.kebabCase(this.name) + '/' + id);
  };

  module.exports = find;

}).call(this);
