// Generated by CoffeeScript 1.9.3
(function() {
  var _, _ajax, findBy;

  _ = require('lodash');

  _ajax = require('../ajax');

  findBy = function(opts) {
    return _ajax.get.apply(this, ['/api/' + _.kebabCase(this.className), opts]);
  };

  module.exports = findBy;

}).call(this);
