// Generated by CoffeeScript 1.9.3
(function() {
  var _ajax, _utilities, where;

  _utilities = require('../utilities');

  _ajax = require('../ajax');

  where = function(opts) {
    return _ajax.get('/api/' + _utilities.pluralKebabCase(this.className), opts);
  };

  module.exports = where;

}).call(this);
