// Generated by CoffeeScript 1.9.3
(function() {
  var _, pluralize, utilities;

  _ = require('lodash');

  pluralize = require('pluralize');

  utilities = {
    pluralKebabCase: function(str) {
      var kebabCaseStr, lastWord, match;
      kebabCaseStr = _.kebabCase(str);
      match = kebabCaseStr.match(/-(\w+)$/);
      if (match) {
        lastWord = match[1];
      } else {
        lastWord = kebabCaseStr;
      }
      return kebabCaseStr.replace(new RegExp(lastWord + '$'), pluralize(lastWord));
    },
    objectToQueryString: function(obj, prefix) {
      var k, p, str, v;
      str = [];
      for (p in obj) {
        if (obj.hasOwnProperty(p)) {
          k = prefix ? prefix + '[' + p + ']' : p;
          v = obj[p];
          str.push(typeof v === 'object' ? this.objectToQueryString(v, k) : encodeURIComponent(k) + '=' + encodeURIComponent(v));
        }
      }
      return str.join('&');
    }
  };

  module.exports = utilities;

}).call(this);
